# Generated by Django 3.0.2 on 2020-02-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='name',
            field=models.CharField(default='SOMETHING', max_length=200),
        ),
    ]
