# Generated by Django 3.0.2 on 2020-02-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_suggestion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
